ver: "2"
packages:
  - package: deb-builder
    source: deb-builder
    version: 'git'
    architecture:
      - amd64
      - arm64
    maintainer: The OSSPkg Team <github@osspkg.com>
    homepage: https://dl.osspkg.com/
    description:
      - Debian package builder
    section: web
    priority: optional
    control:
      build: goppy build --arch=%arch%
    data:
      usr/bin/deb-builder: build/deb-builder_%arch%
    ignore:
      - .git/
