ver: "2"
packages:
  - package: pkg-build
    source: pkg-build
    version: "git"
    architecture:
      - amd64
      - arm64
    maintainer: The OSSPkg Team <github@osspkg.com>
    homepage: https://pkg-build.osspkg.com/
    description:
      - deb && rpm package builder
    section: utils
    priority: optional
    control:
      build: goppy build --arch=%arch%
    data:
      usr/bin/pkg-build: build/pkg-build_%arch%
