package: deb-builder
source: deb-builder
version: '1:0.4.1'
architecture:
  - amd64
  - arm64
maintainer: DewepOnline <deb@dewep.online>
homepage: https://dewep.online/deb-builder
description:
  - Debian package builder
section: web
priority: optional
control:
  build: devtool build --arch=%arch%
data:
  usr/bin/deb-builder: build/deb-builder_%arch%
