package: deb-builder
source: deb-builder
version: '1:0.3.0'
architecture:
  - 386
  - amd64
  - arm
  - arm64
maintainer: DewepOnline <deb@dewep.online>
homepage: https://dewep.online/deb-builder.html
description:
  - Debian package builder
section: web
priority: optional
control:
  depends:
    - systemd
    - ca-certificates
  build: scripts/build.sh
  conffiles:
    - /etc/fdns/config.yaml
  preinst: scripts/preinst.sh
  postinst: scripts/postinst.sh
  prerm: scripts/prerm.sh
  postrm: scripts/postrm.sh
data:
  usr/bin/deb-builder: build/bin/deb-builder_%arch%
  usr/log/deb-builder.log: "+Empty empty log file\n"
